### ISSUE TITLE
Exceptions running example.py:

### ISSUE THREAD

**Issue by ThJohannsen** [RobinMeis/py-fritz-monitor#4]
Hi, when running the example.py script unchanged (git clone or ZIP download) I get the following errors:

```
python3 example.py 
Success connecting to fritz.box on port: 1012
Listening for calls
Traceback (most recent call last):
  File "example.py", line 27, in <module>
    call.parse("09.03.14 21:51:56;CALL;0;12;453423;04829401845;SIP0;") #Simulates outgoing call
  File "/tmp/py-fritz-monitor-master/call_monitor.py", line 76, in parse
    self.call_callback(int(line[2]), "outgoing", self.call_handler[int(line[2])])
  File "/tmp/py-fritz-monitor-master/call_monitor.py", line 35, in call_callback
    self.callback(id, action, details)
TypeError: my_cb() missing 1 required positional argument: 'details'
```

```
python2 example.py 
('Success connecting to', 'fritz.box', 'on port:', '1012')
Listening for calls
Traceback (most recent call last):
  File "example.py", line 27, in <module>
    call.parse("09.03.14 21:51:56;CALL;0;12;453423;04829401845;SIP0;") #Simulates outgoing call
  File "/tmp/py-fritz-monitor-master/call_monitor.py", line 76, in parse
    self.call_callback(int(line[2]), "outgoing", self.call_handler[int(line[2])])
  File "/tmp/py-fritz-monitor-master/call_monitor.py", line 35, in call_callback
    self.callback(id, action, details)
TypeError: my_cb() takes exactly 4 arguments (3 given)
```

 after commenting out the "call.parse" examples and calling my landline:

```
$ python3 example.py 
Success connecting to fritz.box on port: 1012
Listening for calls
Press key to exit
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/py-fritz-monitor-master/call_monitor.py", line 63, in listen
    self.parse (line)
  File "/tmp/py-fritz-monitor-master/call_monitor.py", line 73, in parse
    self.call_callback(int(line[2]), "incoming", self.call_handler[int(line[2])])
  File "/tmp/py-fritz-monitor-master/call_monitor.py", line 35, in call_callback
    self.callback(id, action, details)
TypeError: my_cb() missing 1 required positional argument: 'details'
```

same with pyhton2:

```
$ python2 example.py 
('Success connecting to', 'fritz.box', 'on port:', '1012')
Listening for calls
Press key to exit
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/tmp/py-fritz-monitor-master/call_monitor.py", line 63, in listen
    self.parse (line)
  File "/tmp/py-fritz-monitor-master/call_monitor.py", line 73, in parse
    self.call_callback(int(line[2]), "incoming", self.call_handler[int(line[2])])
  File "/tmp/py-fritz-monitor-master/call_monitor.py", line 35, in call_callback
    self.callback(id, action, details)
TypeError: my_cb() takes exactly 4 arguments (3 given)
```

---------------------------------------------------------------------
my ENVIRONMENT:
$ python3 --version
Python 3.6.5
$ python2 --version
Python 2.7.15

Any ideas?
Danke und Gruß aus Ostfriesland :-)

**Comment by TheGreyDiamond** [comment]
I have the same problem, I hope @RobinMeis can help us out.

**Comment by nicolazilio** [comment]
You can change `my_cb` to the following

```
def my_cb (id, action, details):
    print ("Call: " + action['type'] + " - " + action['from'])
```
